services:
  - name: bridge-app
    type: pserv
    env: node
    buildCommand: NODE_ENV=development pnpm install && NODE_ENV=production pnpm build
    startCommand: pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_NETWORK
        sync: false
      - key: NODE_VERSION
        value: 18.17.1

  - name: nginx
    dockerfilePath: ./nginx/nginx.Dockerfile
    dockerContext: ./nginx
    env: docker
    type: web
    envVars:
      - key: FORWARD_HOST
        fromService:
          name: bridge-app
          type: pserv
          property: host
      - key: FORWARD_PORT
        fromService:
          name: bridge-app
          type: pserv
          property: port
      - key: BASIC_USERNAME
        sync: false
      - key: BASIC_PASSWORD
        sync: false
